import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The curriculum sidebar is generated from the docs/ folder structure: each
// module is a folder with a _category_.json (label + position), and the order
// of pages within a module comes from each page's `sidebar_position`
// frontmatter. Adding a lesson = drop an .mdx into the right module folder.
const sidebars: SidebarsConfig = {
  curriculum: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
